# generated by fastapi-codegen:
#   filename:  juju_api.yml
#   timestamp: 2021-04-28T16:23:11+00:00

from __future__ import annotations

from datetime import date
from typing import Optional

from pydantic import BaseModel, SecretStr


class VoucherInfo(BaseModel):
    code: str
    serial_no: str
    amount: int
    time: Optional[date] = None
    comment: Optional[str] = None
    vtype: Optional[str] = None


class AccountInfo(BaseModel):
    name: str
    password: SecretStr


class NormalResponsesData(BaseModel):
    code: int
    message: str
